version: '3'
services:
    django:
        build:
            context: .
        # test comment
        #Note that we use the host.docker.internal  value to refer to the remote host.
        #In Docker for Windows and Docker for Mac, it automatically resolves to the internal address of the host, letting you easily connect to it from the container.
        restart: always
        env_file:
            -   ./.env
        depends_on:
            - db
        ports:
            - "8000:8000"
            - "4000:4000" #VSCODE Debug port
        volumes:
            - ./mhttc:/mhttc:delegated
    db:
        image: mysql:5.7
        env_file:
            - ./.env
        #restart: always
        volumes:
            - mysql-volume:/var/lib/mysql
            - ../logs:/var/log/mysql
            - ./override-mysql:/etc/mysql/mysql.conf.d
        ports:
            - "3306:3306"
volumes:
    mysql-volume:
    logs-volume:

