version: '3'
services:
    django:
        build:
            context: .
        # test comment
        #Note that we use the host.docker.internal  value to refer to the remote host.
        #In Docker for Windows and Docker for Mac, it automatically resolves to the internal address of the host, letting you easily connect to it from the container.
        restart: always
        env_file:
            -   ./.env
        depends_on:
            - cloudsql-proxy
        ports:
            - "80:8000"
            - "4000:4000" #VSCODE Debug port
        volumes:
            - ./mhttc:/mhttc:delegated
            - ./static:/static:delegated
    cloudsql-proxy:
        container_name: mhttc-cloudsql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.7
        command: som-mhttcnco:us-west1:mhhtc-intranet --port=5432 -a 0.0.0.0 -c "/secrets/cloudsql/credentials.json"
        volumes:
            - ./mhhtc-cloud-sql-client.json:/secrets/cloudsql/credentials.json
        ports:
            - "3306:5432"
volumes:
    mhttc-logs-volume:

