# Generated by Django 3.1.7 on 2021-04-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201106_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.IntegerField(blank=True, choices=[(0, 'Public'), (1, 'Private')], default=0),
        ),
    ]
