# Generated by Django 3.2 on 2021-04-27 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20210422_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='consider_ascertained',
            field=models.TextField(blank=True, help_text='How were these considerations ascertained (e.g., formal evaluation, needs/readiness assessment)?', null=True),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='consider_clinical_factors_barriers',
            field=models.TextField(default=None, help_text='Individual clinician factors (e.g., alignment with existing practice; complexity)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='consider_org_factors_barriers',
            field=models.TextField(default=1, help_text='Organizational factors—internal to the organization (e.g., leadership; readiness)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='consider_system_factors_barriers',
            field=models.TextField(default=1, help_text='System factors--external to the organization (e.g., financing; mandates, community, culture)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='need',
            field=models.TextField(default=1, help_text='What is the need/rationale for this project?  Why/how did you decide to do this project?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='target_audience_relations',
            field=models.IntegerField(blank=True, choices=[(1, 'Single individuals from multiple organizations'), (2, 'Multiple individuals within one organization'), (3, 'Multiple individuals or teams from multiple organizations')], default=1, help_text='Specify audience relationship to one another (Choose one):'),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='target_audience_settings',
            field=models.TextField(default=1, help_text='Specify the audience’s setting (e.g., emergency departments, schools, opioid treatment programs):'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='target_audience_ta_recipients',
            field=models.TextField(default=1, help_text='How will your target audience/TA recipients be recruited?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='implement_strategy_description',
            field=models.TextField(help_text='Describe the sequence of the planned Implementation Strategies, step by step:'),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='target_audience_disciplines',
            field=models.TextField(help_text='Specify discipline(s) of individuals: '),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='target_audience_roles',
            field=models.TextField(help_text='Specify roles of individuals: '),
        ),
        migrations.CreateModel(
            name='StrategyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(blank=True, help_text='Category', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategy_type_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategy_type_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategy_type', to='main.strategytype'),
        ),
    ]
