# Generated by Django 3.2 on 2021-04-27 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210427_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='strategy_type',
        ),
        migrations.AddField(
            model_name='strategy',
            name='strategy_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategy_type', to='main.strategytype'),
        ),
    ]
