# Generated by Django 3.2 on 2021-04-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_formtemplate_other_relevant_issues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='visibility',
        ),
    ]
