# Generated by Django 3.2 on 2021-05-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_project_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='need',
            field=models.TextField(help_text='What is the need/rationale for this project?  Why/how did you decide to do this project?', null=True),
        ),
    ]
