# Generated by Django 3.2 on 2021-05-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_formtemplate_need'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='consider_clinical_factors',
            field=models.TextField(help_text='Individual clinician factors (e.g., alignment with existing practice; complexity)', null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='consider_clinical_factors_barriers',
            field=models.TextField(help_text='Individual clinician factors (e.g., alignment with existing practice; complexity)', null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='consider_org_factors',
            field=models.TextField(help_text='Organizational factors—internal to the organization (e.g., leadership; readiness)', null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='consider_org_factors_barriers',
            field=models.TextField(help_text='Organizational factors—internal to the organization (e.g., leadership; readiness)', null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='consider_system_factors',
            field=models.TextField(help_text='System factors--external to the organization (e.g., financing; mandates, community, culture)', null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='consider_system_factors_barriers',
            field=models.TextField(help_text='System factors--external to the organization (e.g., financing; mandates, community, culture)', null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='evaluation_proximal_training_outcome',
            field=models.ManyToManyField(null=True, related_name='form_training_outcome', related_query_name='form_training_outcome', to='main.TrainingOutcome'),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='implement_strategy',
            field=models.ManyToManyField(default=None, null=True, related_name='form_template1', related_query_name='form_template1', to='main.Strategy'),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='outcome_adoption',
            field=models.TextField(help_text='Number of providers? How will you be measuring it?', null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='outcome_cost',
            field=models.TextField(help_text='Cost. How will you keep track of it?', null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='outcome_effectiveness',
            field=models.TextField(help_text='Effectiveness of Intervention/Program/Services (w/consumers), how will you measure it?', null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='outcome_maintenance',
            field=models.TextField(help_text='Maintenance/Sustainment.', null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='outcome_other',
            field=models.TextField(help_text='Any other measures being planned?', null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='outcome_quality',
            field=models.TextField(help_text='Implementation Fidelity/Adherence/Quality. How will you be measuring it?', null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='outcome_reach',
            field=models.TextField(help_text='Reach (# or percentage of population, what is the population, and how will you be measuring the outcome?', null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='target_audience_disciplines',
            field=models.TextField(help_text='Specify discipline(s) of individuals: ', null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='target_audience_roles',
            field=models.TextField(help_text='Specify roles of individuals: ', null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='target_audience_settings',
            field=models.TextField(help_text='Specify the audience’s setting (e.g., emergency departments, schools, opioid treatment programs):', null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='target_audience_ta_recipients',
            field=models.TextField(help_text='How will your target audience/TA recipients be recruited?', null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='target_audience_who',
            field=models.TextField(help_text='Who is the audience (including type of organizations)', null=True),
        ),
    ]
