# Generated by Django 3.2 on 2021-05-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210511_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='end_date',
            field=models.DateTimeField(help_text='project end date', null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='start_date',
            field=models.DateTimeField(help_text='project start date', null=True),
        ),
    ]
