# Generated by Django 3.2 on 2021-05-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210511_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='end_date',
            field=models.TextField(help_text='project end date', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Project Title'),
        ),
    ]
