# Generated by Django 3.2 on 2021-05-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210512_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='brief_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
