# Generated by Django 3.2 on 2021-05-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_strategy_brief_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='evaluation_planned_enrollment_individual',
            field=models.CharField(blank=True, help_text='How many individual planned for enrollment?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='evaluation_planned_enrollment_organization',
            field=models.CharField(blank=True, help_text='How many organization planned for enrollment?', max_length=255, null=True),
        ),
    ]
