# Generated by Django 3.2 on 2021-06-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210512_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='planned_number_units',
            field=models.PositiveIntegerField(blank=True, help_text='Planned number of units', null=True),
        ),
    ]
