# Generated by Django 3.2 on 2021-06-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_strategy_planned_number_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='planned_number_units',
            field=models.CharField(blank=True, help_text='Planned number of units', max_length=500, null=True),
        ),
    ]
