# Generated by Django 3.2 on 2021-06-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_strategy_planned_number_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='target_audience_relations_other',
            field=models.TextField(default='', help_text='If Other, please specify?'),
        ),
    ]
