# Generated by Django 3.2 on 2021-04-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_center_center_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='center_group',
        ),
        migrations.DeleteModel(
            name='CenterGroup',
        ),
    ]
