# Generated by Django 3.2 on 2021-04-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210428_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('full_menu_access', 'Has Access to full left menu?')]},
        ),
    ]
