# Generated by Django 3.2 on 2021-05-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210511_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CenterGroup',
        ),
    ]
